In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mlxtend.preprocessing import TransactionEncoder
from apyori import apriori
from sklearn.preprocessing import OneHotEncoder

In [ ]:
data = pd.read_csv("/data/basket_analysis_dataset.csv")
data

0       1       2       3       4       5       6
0     Bread    Wine    Eggs    Meat  Cheese  Pencil  Diaper
1     Bread  Cheese    Meat  Diaper    Wine    Milk  Pencil
2    Cheese    Meat    Eggs    Milk    Wine     NaN     NaN
3    Cheese    Meat    Eggs    Milk    Wine     NaN     NaN
4      Meat  Pencil    Wine     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...     ...     ...
310   Bread    Eggs  Cheese     NaN     NaN     NaN     NaN
311    Meat    Milk  Pencil     NaN     NaN     NaN     NaN
312   Bread  Cheese    Eggs    Meat  Pencil  Diaper    Wine
313    Meat  Cheese     NaN     NaN     NaN     NaN     NaN
314    Eggs    Wine   Bagel   Bread    Meat     NaN     NaN

[315 rows x 7 columns]

In [ ]:
count0 = data["0"].value_counts()
count1 = data["1"].value_counts()
count2 = data["2"].value_counts()
count3 = data["3"].value_counts()
count4 = data["4"].value_counts()
count5 = data["5"].value_counts()
count6 = data["6"].value_counts()

count = count0+count1+count2+count3+count4+count5+count6

print(count)

Bagel     134
Bread     159
Cheese    158
Diaper    128
Eggs      138
Meat      150
Milk      158
Pencil    114
Wine      138
dtype: int64


In [ ]:
records  = []
for i in range(1, 315):
    records .append([str(data.values[i, j]) for j in range(0,7)])
    

In [ ]:
print(type(records))


<class 'list'>


In [ ]:
association_rules = apriori(records, min_support=0.02, min_confidence=0.3, min_lift=2)
association_results = list(association_rules)

In [ ]:
print("{} ilişki türetilmiştir".format(len(association_results)))


32 ilişki türetilmiştir


In [ ]:
for item in association_results:
    # first index of the inner list
    # Contains base item and add item
    pair = item[0]
    items = [x for x in pair]
    print("Rule: " + items[0] + " -> " + items[1])

    # second index of the inner list
    print("Support: " + str(item[1]))

  
    print("=====================================")

Rule: Milk -> Eggs
Support: 0.06369426751592357
Rule: Milk -> Cheese
Support: 0.15286624203821655
Rule: Bread -> Meat
Support: 0.041401273885350316
Rule: Pencil -> Milk
Support: 0.028662420382165606
Rule: Wine -> Milk
Support: 0.03184713375796178
Rule: Eggs -> Meat
Support: 0.03821656050955414
Rule: Wine -> Eggs
Support: 0.03503184713375796
Rule: Wine -> Pencil
Support: 0.03184713375796178
Rule: Wine -> Eggs
Support: 0.028662420382165606
Rule: Wine -> Pencil
Support: 0.025477707006369428
Rule: Milk -> Bread
Support: 0.03503184713375796
Rule: Pencil -> Milk
Support: 0.041401273885350316
Rule: Wine -> Milk
Support: 0.050955414012738856
Rule: Pencil -> Milk
Support: 0.03821656050955414
Rule: Wine -> Pencil
Support: 0.050955414012738856
Rule: Milk -> Bread
Support: 0.025477707006369428
Rule: Wine -> Milk
Support: 0.03503184713375796
Rule: Pencil -> Milk
Support: 0.03503184713375796
Rule: Wine -> Milk
Support: 0.041401273885350316
Rule: Wine -> Pencil
Support: 0.044585987261146494
Rule: Win

In [ ]:
ohe = OneHotEncoder()

In [ ]:
datao = ohe.fit_transform(data).toarray()
print(datao)

[[0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 1.]
 ...
 [0. 1. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
